name: Production Deployment
on:
   workflow_dispatch:
    inputs:
      Tag-Name:
        description: 'e.g., PROD_1.0.0'
        required: true
      Release-Name:
        description: 'e.g., PROD v1.0.0'
        required: true
      Auth-Key:
        description: 'Authentication key to start the workflow'
        required: true

jobs:
  geo-stem_PROD_auth:
    runs-on: ubuntu-latest
    steps:
      - name: Check Auth-Key
        run: |
          if [ "${{ github.event.inputs.Auth-Key }}" != "${{ secrets.AUTH_KEY }}" ]; then
            echo "Invalid Auth-Key"
            exit 1
          else
            echo "Key correct. Proceeding with the workflow."
          fi  
  
  geo-stem_PROD_migrator:
    runs-on: self-hosted
    needs: geo-stem_PROD_auth   
    steps:
      - name: Pull latest code from master branch
        run: |
          cd C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/PROD/aspnet-core/src/GeoStem.DbMigrator
          git pull origin master
 
      - name: Build DbMigrator
        run: dotnet build --configuration Debug GeoStem.DbMigrator.csproj
        working-directory: C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/PROD/aspnet-core/src/GeoStem.DbMigrator
 
      - name: Run DbMigrator
        run: dotnet run --configuration Debug --project GeoStem.DbMigrator.csproj
        working-directory: C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/PROD/aspnet-core/src/GeoStem.DbMigrator
  
  geo-stem_PROD_asp:
    runs-on: self-hosted
    needs: geo-stem_PROD_migrator
    env:
     AZURE_WEBAPP_NAME: gs-prod-api
     AZURE_WEBAPP_PACKAGE_PATH: src\GeoStem.HttpApi.Host\published
     CONFIGURATION: Release
     DOTNET_CORE_VERSION: 8.0.x
     WORKING_DIRECTORY: aspnet-core\src\GeoStem.HttpApi.Host
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: stage
        publish-profile: ${{ secrets.GS_AZURE_API_PUBLISH_PROFILE_PROD }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  geo-stem_PROD_angular:
    runs-on: self-hosted
    needs: geo-stem_PROD_asp
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3       
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install dependencies
      run: yarn 
      working-directory: angular
    - name: Run build script
      run: yarn build:prod
      working-directory: angular
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: gs-prod-web
        slot-name: stage
        publish-profile: ${{ secrets.GS_AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
        package: angular/dist/GeoStem
            
  create_release:
    runs-on: self-hosted
    needs: geo-stem_PROD_angular
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Indian Date
        id: set_date
        run: |
            $currentTimestamp = (Get-Date).AddHours(5.5).ToString('dd-MM-yyyy-HH-mm-ss')
            echo "current_timestamp=$currentTimestamp" >> $env:GITHUB_ENV        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.Tag-Name }}-${{ env.current_timestamp }}
          release_name: ${{ github.event.inputs.Release-Name }}
          draft: false
          prerelease: false
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
