name: PREPROD Deployment
on:
   push:
    branches:
      - stage
   workflow_dispatch:
concurrency:
  group: preprod-release-flow # cancel queued running
  cancel-in-progress: true   

jobs:  
  geo-stem_PREPROD_migrator:
    runs-on: self-hosted   
    steps:
      - name: Pull latest code from stage branch
        run: |
          cd C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/PREPROD/aspnet-core/src/GeoStem.DbMigrator
          git pull origin stage
      - name: Build DbMigrator
        run: dotnet build --configuration Debug GeoStem.DbMigrator.csproj
        working-directory: C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/PREPROD/aspnet-core/src/GeoStem.DbMigrator 
      - name: Run DbMigrator
        run: dotnet run --configuration Debug --project GeoStem.DbMigrator.csproj
        working-directory: C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/PREPROD/aspnet-core/src/GeoStem.DbMigrator
  
  geo-stem_PREPROD_asp:
    runs-on: self-hosted
    needs: geo-stem_PREPROD_migrator
    env:
     AZURE_WEBAPP_NAME: gs-preprod-api
     AZURE_WEBAPP_PACKAGE_PATH: src\GeoStem.HttpApi.Host\published
     CONFIGURATION: Release
     DOTNET_CORE_VERSION: 8.0.x
     WORKING_DIRECTORY: aspnet-core\src\GeoStem.HttpApi.Host
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_GS_PREPROD_API }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  geo-stem_PREPROD_angular:
    runs-on: self-hosted
    needs:   geo-stem_PREPROD_asp
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install dependencies
      run: yarn 
      working-directory: angular
    - name: Run build script
      run: yarn build:preprod
      working-directory: angular
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: gs-preprod
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_GS_PREPROD }}
        package: angular/dist/preprod      
  
    - name: webhook_scaleup
      shell: powershell
      run: |
          $url = "https://f61cc6d6-43bf-4efe-b750-856482330205.webhook.cid.azure-automation.net/webhooks?token=uGxpIwv2L9QPQ7RP2TbflKxmlnbY2YOVQAB57%2b%2b8XSU%3d"
          Invoke-WebRequest -Uri $url -Method POST 

    - name: notify
      shell: powershell
      run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"${{ github.repository }}, ${{ github.workflow }} \n \n Completed Successfully!"}]}}]}'
