name: QA Deployment
on:
   push:
    branches:
      - dev
   workflow_dispatch:
concurrency:
  group: qa-release-flow # cancel queued running
  cancel-in-progress: true
jobs:  
  geo-stem_QA_migrator:
    runs-on: self-hosted
    steps:
      - name: notify
        shell: powershell
        run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"${{ github.repository }}, ${{ github.workflow }} \n \n Started"}]}}]}'
      - name: Pull latest code from dev branch
        run: |
          cd C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/QA/aspnet-core/src/GeoStem.DbMigrator
          git pull origin dev
 
      - name: Build DbMigrator
        run: dotnet build --configuration Debug GeoStem.DbMigrator.csproj
        working-directory: C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/QA/aspnet-core/src/GeoStem.DbMigrator
 
      - name: Run DbMigrator
        run: dotnet run --configuration Debug --project GeoStem.DbMigrator.csproj
        working-directory: C:/Users/sh-auto-vm-user/source/actions-runner/SpeeHive/Geostem/QA/aspnet-core/src/GeoStem.DbMigrator
      - name: notify cancelled
        if: cancelled()
        shell: powershell
        run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"**${{ github.repository }}, ${{ github.workflow }} \n \n Cancelled!**"}]}}]}'
      - name: notify failure
        if: failure()
        shell: powershell
        run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"**${{ github.repository }}, ${{ github.workflow }} \n \n Failed!**"}]}}]}' 
  geo-stem_QA_asp:
    runs-on: self-hosted
    needs: geo-stem_QA_migrator
    env:
     AZURE_WEBAPP_NAME: geostem-qa-api
     AZURE_WEBAPP_PACKAGE_PATH: src\GeoStem.HttpApi.Host\published
     CONFIGURATION: Release
     DOTNET_CORE_VERSION: 8.0.x
     WORKING_DIRECTORY: aspnet-core\src\GeoStem.HttpApi.Host
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.geostem_qa_api_AB31 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: notify cancelled
      if: cancelled()
      shell: powershell
      run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"**${{ github.repository }}, ${{ github.workflow }} \n \n Cancelled!"}]}}]}'
    - name: notify failure
      if: failure()
      shell: powershell
      run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"**${{ github.repository }}, ${{ github.workflow }} \n \n Failed!**"}]}}]}' 
  geo-stem_QA_angular:
    runs-on: self-hosted
    needs: geo-stem_QA_asp

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn 
      working-directory: angular

    - name: Run build script
      run: yarn build:qa
      working-directory: angular

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_QA }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}
        package: angular/dist/qa
    
    - name: Push changes
      id: push_changes
      run: |
          git push
          $latestTag = git describe --tags $(git rev-list --tags --max-count=1)
          git push origin $latestTag
          echo "::set-output name=latest_tag::$latestTag"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: notify
      shell: powershell
      run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"${{ steps.push_changes.outputs.latest_tag }} ${{ github.repository }}, ${{ github.workflow }} \n \n Completed Successfully!"}]}}]}'
      
    - name: notify failure
      if: failure()
      shell: powershell
      run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"**${{ github.repository }}, ${{ github.workflow }} \n \n Failed!**"}]}}]}' 
    - name: notify cancelled
      if: cancelled()
      shell: powershell
      run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"**${{ github.repository }}, ${{ github.workflow }} \n \n Cancelled!**"}]}}]}'
