name: QA Deployment
on:
  push:
    branches:
    - dev
  workflow_dispatch:
    inputs:
      reportengine-api-branch:
        description: 'The branch for reportengine-api'
        required: true
        default: 'dev'

concurrency:
  group: re-qa-flow # cancel queued running
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: gp-reportengine-qa-api
  AZURE_WEBAPP_PACKAGE_PATH: ReportService\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: mod\ReportService\ReportService.csproj

jobs:
  build:
    runs-on: self-hosted
    environment: QA
    steps:
    - name: Determine branches to use
      id: branches
      shell: powershell
      run: |
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
          "reportengine_api_branch=${{ github.event.inputs.reportengine-api-branch }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
          "reportengine_api_branch=dev" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }
    - name: Checkout gp-reportengine-api
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        repository: Geoservedmcc/gp-reportengine-api
        path: gp-reportengine-api
        ref: ${{ steps.branches.outputs.reportengine_api_branch }}

    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    
    - name: Deploy to IIS on Azure VM using MSDeploy
      shell: powershell
      run: |
        & "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath="${{ github.workspace }}\${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" -dest:contentPath="${{ secrets.QA_IIS_SITE_NAME }}",ComputerName="https://${{ secrets.QA_VM_IP }}:8172/msdeploy.axd?site=${{ secrets.QA_IIS_SITE_NAME }}",userName="${{ secrets.QA_VM_USERNAME }}",password="${{ secrets.QA_VM_PASSWORD }}",authType="Basic" -verbose -enableRule:DoNotDeleteRule -enableRule:AppOffline -allowUntrusted
    # - name: Deploy to Azure WebApp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #     publish-profile: ${{ secrets.REPORTENGINE_AZURE_API_PUBLISH_PROFILE_QA }}
    #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  tag:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
         fetch-depth: '0'
      
      - name: Get Latest Tag
        id: get_tag
        run: |
          $latestTag = git describe --tags $(git rev-list --tags --max-count=1)
          echo "::set-output name=tag::$latestTag"
      
      - name: Increment Tag
        id: increment_tag
        run: |
          $tag = "${{ steps.get_tag.outputs.tag }}"
          $versionParts = $tag.Split('.')
          $lastPart = [int]$versionParts[-1]
          $newLastPart = $lastPart + 1
          $newTag = "$($versionParts[0]).$($versionParts[1]).$newLastPart"
          echo "::set-output name=new_tag::$newTag"
      
      - name: Create New Tag
        run: |
          $newTag = "${{ steps.increment_tag.outputs.new_tag }}"
          git tag $newTag
          git push origin $newTag
      
      - name: notify
        shell: powershell
        run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"${{ steps.increment_tag.outputs.new_tag }} ${{ github.repository }}, ${{ github.workflow }} \n \n Completed Successfully!"}]}}]}'
