name: QA Deployment

on:
  push:
    branches:
      - dev
  workflow_dispatch:
concurrency:
  group: qa-flow # cancel queued running
  cancel-in-progress: true

jobs:
  gp-website_QA_build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
    - name: Install dependencies
      run: npm install --force
    - name: Run build script
      run: npm run build:qa2
    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: deploy to vm
      shell: powershell
      run: |
        .\upload.ps1 -ftpUser '${{ secrets.FTP_USER_QA }}' -ftpPassword '${{ secrets.FTP_PASSWORD_QA }}' -serverIp '${{ secrets.APP_SERVER_IP_QA }}' -sourceFolderName 'qa' -subFolder 'website'
    - name: notify
      shell: powershell
      run: |
          $url = "${{ secrets.TEAMS_HOOK }}"
          Invoke-WebRequest -Uri $url -Method POST -ContentType "application/json" -Body '{"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.text","content":{"type":"message","body":[{"type":"text","text":"${{ steps.increment_tag.outputs.new_tag }} ${{ github.repository }}, ${{ github.workflow }} \n \n Completed Successfully!"}]}}]}'
  
  gp-website_QA_regression:
   runs-on: self-hosted
   needs: gp-website_QA_build
   steps:
    - name: Trigger
      uses: peter-evans/repository-dispatch@v1
      with:
         token: ${{ secrets.V_GITHUB_PAT }} 
         repository: Geoservedmcc/vps_automation
         event-type: qa-deployment-completed
